http:
  swagger:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

mysql:
  database: kcloud
  password: 12345678
  level: info

redis:
  password: 12345678

mongo:
  password: 12345678

jwt:
  secret: 12345678
