// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "get": {
                "description": "获取账户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "账户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键字",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "x-enum-varnames": [
                            "StatusNormal",
                            "StatusDisabled",
                            "StatusDeleted"
                        ],
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.Accounts"
                        }
                    }
                }
            },
            "post": {
                "description": "账户创建",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "账户创建",
                "parameters": [
                    {
                        "description": "账户创建请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/account/change/email": {
            "put": {
                "description": "账户修改邮箱",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "账户修改邮箱",
                "parameters": [
                    {
                        "description": "账户修改邮箱请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.ChangeEmailRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/account/change/mobile": {
            "put": {
                "description": "账户修改手机号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "账户修改手机号",
                "parameters": [
                    {
                        "description": "账户修改手机号请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.ChangeMobileRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/account/change/password": {
            "put": {
                "description": "账户修改密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "账户修改密码",
                "parameters": [
                    {
                        "description": "账户修改密码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.ChangePasswordRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/account/detail": {
            "get": {
                "description": "获取账户详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "账户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.Account"
                        }
                    }
                }
            }
        },
        "/account/{id}": {
            "delete": {
                "description": "账户删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "账户删除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/auth/gotp/generate": {
            "post": {
                "description": "生成谷歌验证器密钥二维码base64",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "生成谷歌验证器密钥二维码base64",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/google.GenerateResponse"
                        }
                    }
                }
            }
        },
        "/auth/gotp/verify": {
            "post": {
                "description": "验证谷歌验证器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "验证谷歌验证器",
                "parameters": [
                    {
                        "description": "验证请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/google.ValidateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/google.ValidateResponse"
                        }
                    }
                }
            }
        },
        "/auth/kick": {
            "post": {
                "description": "踢人下线",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "踢人下线",
                "parameters": [
                    {
                        "description": "踢人请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jwt.KickRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jwt.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/jwt.Jwt"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "登出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "登出",
                "parameters": [
                    {
                        "description": "登出请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jwt.LogoutRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "刷新令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "刷新令牌",
                "parameters": [
                    {
                        "description": "刷新请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jwt.RefreshRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notifier/channal": {
            "get": {
                "description": "查询通道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifier"
                ],
                "summary": "查询通道",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "创建时间",
                        "name": "created_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键字",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "email",
                            "dingtalk",
                            "telegram"
                        ],
                        "type": "string",
                        "description": "供应商类型",
                        "name": "provider_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "normal",
                            "disabled"
                        ],
                        "type": "string",
                        "x-enum-varnames": [
                            "StatusNormal",
                            "StatusDisabled"
                        ],
                        "description": "通道状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/channal.Channels"
                        }
                    }
                }
            },
            "post": {
                "description": "创建通道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifier"
                ],
                "summary": "创建通道",
                "parameters": [
                    {
                        "description": "创建通道请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/channal.CreateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/channal.CreateResponse"
                        }
                    }
                }
            }
        },
        "/notifier/channal/detail": {
            "get": {
                "description": "查询通道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifier"
                ],
                "summary": "查询通道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ApiKey",
                        "name": "api_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/channal.Channal"
                        }
                    }
                }
            }
        },
        "/notifier/channal/{id}": {
            "delete": {
                "description": "删除通道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifier"
                ],
                "summary": "删除通道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "通道Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/notifier/message": {
            "get": {
                "description": "消息列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifier"
                ],
                "summary": "消息列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "消息类型",
                        "name": "created_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键字",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "消息等级",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/message.Messages"
                        }
                    }
                }
            },
            "put": {
                "description": "更新消息状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifier"
                ],
                "summary": "更新消息状态",
                "parameters": [
                    {
                        "description": "更新消息状态请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/message.ChangeStatusRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/notifier/message/send": {
            "post": {
                "description": "发送消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifier"
                ],
                "summary": "发送消息",
                "parameters": [
                    {
                        "type": "string",
                        "name": "api_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "signature",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "timestamp",
                        "in": "query"
                    },
                    {
                        "description": "创建消息请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/message.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/notifier/message/{id}": {
            "delete": {
                "description": "删除消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifier"
                ],
                "summary": "删除消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/security/audit": {
            "post": {
                "description": "账户最近登录详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security"
                ],
                "summary": "账户最近登录详情",
                "parameters": [
                    {
                        "description": "账户登录环境请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/audit.LastLoginDetailRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/security/captcha/email/send": {
            "post": {
                "description": "发送邮箱验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/security/captcha/email/verify": {
            "post": {
                "description": "验证邮箱验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security"
                ],
                "summary": "验证邮箱验证码",
                "parameters": [
                    {
                        "description": "验证邮箱验证码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/captcha.VerifyEmailCodeRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/captcha.VerifyEmailCodeResponse"
                        }
                    }
                }
            }
        },
        "/security/captcha/mobile/send": {
            "post": {
                "description": "发送手机验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security"
                ],
                "summary": "发送手机验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/security/captcha/mobile/verify": {
            "post": {
                "description": "验证手机验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security"
                ],
                "summary": "验证手机验证码",
                "parameters": [
                    {
                        "description": "验证手机验证码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/captcha.VerifyMobileCodeRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/captcha.VerifyMobileCodeResponse"
                        }
                    }
                }
            }
        },
        "/security/device": {
            "get": {
                "description": "设备列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security"
                ],
                "summary": "设备列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账户id",
                        "name": "account_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备id",
                        "name": "device_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/security/device/bind": {
            "post": {
                "description": "设备绑定",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security"
                ],
                "summary": "设备绑定",
                "parameters": [
                    {
                        "description": "设备绑定请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/device.BindRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/security/device/change": {
            "put": {
                "description": "设备更换",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security"
                ],
                "summary": "设备更换",
                "parameters": [
                    {
                        "description": "设备更换请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/device.ChangeRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/security/device/unbind": {
            "post": {
                "description": "设备解绑",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security"
                ],
                "summary": "设备解绑",
                "parameters": [
                    {
                        "description": "设备解绑请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/device.UnbindRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "account.Account": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "deleted_at": {
                    "description": "删除时间",
                    "type": "integer"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "自增主键",
                    "type": "integer"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "role": {
                    "description": "角色",
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.Role"
                        }
                    ]
                },
                "status": {
                    "description": "状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.Status"
                        }
                    ]
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "username": {
                    "description": "用户名\nuniqueIndex:idx_deleted_at: 唯一索引, 避免软删除的数据重复",
                    "type": "string"
                }
            }
        },
        "account.Accounts": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "用户列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/account.Account"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "account.ChangeEmailRequest": {
            "type": "object",
            "required": [
                "email",
                "security_code"
            ],
            "properties": {
                "email": {
                    "description": "新邮箱",
                    "type": "string"
                },
                "security_code": {
                    "description": "安全码",
                    "type": "string"
                }
            }
        },
        "account.ChangeMobileRequest": {
            "type": "object",
            "required": [
                "mobile",
                "security_code"
            ],
            "properties": {
                "mobile": {
                    "description": "新手机号",
                    "type": "string"
                },
                "security_code": {
                    "description": "安全码",
                    "type": "string"
                }
            }
        },
        "account.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "password",
                "security_code"
            ],
            "properties": {
                "password": {
                    "description": "新密码",
                    "type": "string"
                },
                "security_code": {
                    "description": "安全码",
                    "type": "string"
                }
            }
        },
        "account.CreateRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 24,
                    "minLength": 3
                }
            }
        },
        "audit.LastLoginDetailRequest": {
            "type": "object",
            "required": [
                "device_id",
                "device_name",
                "user_agent"
            ],
            "properties": {
                "device_id": {
                    "description": "设备id",
                    "type": "string"
                },
                "device_name": {
                    "description": "设备名称",
                    "type": "string"
                },
                "user_agent": {
                    "description": "用户客户端",
                    "type": "string"
                }
            }
        },
        "captcha.VerifyEmailCodeRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                }
            }
        },
        "captcha.VerifyEmailCodeResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "description": "是否验证成功",
                    "type": "boolean"
                },
                "ttl": {
                    "description": "剩余时间",
                    "type": "integer"
                }
            }
        },
        "captcha.VerifyMobileCodeRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                }
            }
        },
        "captcha.VerifyMobileCodeResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "description": "是否验证成功",
                    "type": "boolean"
                },
                "ttl": {
                    "description": "剩余时间",
                    "type": "integer"
                }
            }
        },
        "channal.Channal": {
            "type": "object",
            "properties": {
                "account_id": {
                    "description": "账户Id",
                    "type": "integer"
                },
                "api_key": {
                    "description": "ApiKey",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "description": {
                    "description": "通道描述",
                    "type": "string"
                },
                "id": {
                    "description": "消息Id",
                    "type": "string"
                },
                "limiter": {
                    "description": "限速器"
                },
                "limiter_type": {
                    "description": "限速器类型",
                    "type": "string"
                },
                "name": {
                    "description": "通道名称",
                    "type": "string"
                },
                "provider": {
                    "description": "供应商"
                },
                "provider_type": {
                    "description": "供应商类型",
                    "type": "string"
                },
                "secret": {
                    "description": "密钥",
                    "type": "string"
                },
                "status": {
                    "description": "通道状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/channal.Status"
                        }
                    ]
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "integer"
                }
            }
        },
        "channal.Channels": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "通道列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/channal.Channal"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "channal.CreateRequest": {
            "type": "object",
            "required": [
                "name",
                "provider",
                "provider_type"
            ],
            "properties": {
                "description": {
                    "description": "通道描述",
                    "type": "string"
                },
                "limiter": {
                    "description": "限速器\nsliding_window: {\"window\":0, \"limit\":0}\ntoken_bucket: {\"capacity\":0, \"rate\":0}",
                    "type": "string"
                },
                "limiter_type": {
                    "description": "限速器类型",
                    "type": "string",
                    "enum": [
                        "sliding_window",
                        "token_bucket"
                    ]
                },
                "name": {
                    "description": "通道名称",
                    "type": "string"
                },
                "provider": {
                    "description": "供应商\nemail: {\"from\":\"\", \"smtp_server\":\"\", \"smtp_port\":0, \"smtp_username\":\"\", \"smtp_password\":\"\"}\ndingtalk: {\"webhook\":\"\", \"secret\":\"\"}\nlark: {\"webhook\":\"\", \"secret\":\"\"}\ntelegram: {\"token\":\"\", \"chat_id\":\"\"}",
                    "type": "string"
                },
                "provider_type": {
                    "description": "供应商类型",
                    "type": "string",
                    "enum": [
                        "email",
                        "dingtalk",
                        "lark",
                        "telegram"
                    ]
                },
                "sign": {
                    "description": "是否加签",
                    "type": "boolean"
                }
            }
        },
        "channal.CreateResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "secret": {
                    "type": "string"
                }
            }
        },
        "channal.Status": {
            "type": "string",
            "enum": [
                "normal",
                "disabled"
            ],
            "x-enum-varnames": [
                "StatusNormal",
                "StatusDisabled"
            ]
        },
        "common.Role": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-varnames": [
                "RoleUser",
                "RoleAdmin"
            ]
        },
        "common.Status": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "StatusNormal",
                "StatusDisabled",
                "StatusDeleted"
            ]
        },
        "device.BindRequest": {
            "type": "object",
            "required": [
                "account_id",
                "device_id",
                "name",
                "type"
            ],
            "properties": {
                "account_id": {
                    "description": "账户id",
                    "type": "string"
                },
                "device_id": {
                    "description": "设备id",
                    "type": "string"
                },
                "name": {
                    "description": "设备名称",
                    "type": "string"
                },
                "type": {
                    "description": "设备类型",
                    "type": "string"
                }
            }
        },
        "device.ChangeRequest": {
            "type": "object",
            "required": [
                "account_id",
                "device_id",
                "name",
                "type"
            ],
            "properties": {
                "account_id": {
                    "description": "账户id",
                    "type": "string"
                },
                "device_id": {
                    "description": "设备id",
                    "type": "string"
                },
                "name": {
                    "description": "设备名称",
                    "type": "string"
                },
                "type": {
                    "description": "设备类型",
                    "type": "string"
                }
            }
        },
        "device.UnbindRequest": {
            "type": "object",
            "required": [
                "account_id",
                "device_id"
            ],
            "properties": {
                "account_id": {
                    "description": "账户id",
                    "type": "string"
                },
                "device_id": {
                    "description": "设备id",
                    "type": "string"
                }
            }
        },
        "google.GenerateResponse": {
            "type": "object",
            "properties": {
                "qr_code": {
                    "description": "二维码base64",
                    "type": "string"
                },
                "secret": {
                    "description": "谷歌验证器密钥",
                    "type": "string"
                }
            }
        },
        "google.ValidateRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "description": "谷歌验证码",
                    "type": "string"
                }
            }
        },
        "google.ValidateResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "description": "是否验证通过",
                    "type": "boolean"
                },
                "security_code": {
                    "description": "安全码",
                    "type": "string"
                }
            }
        },
        "jwt.Jwt": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "访问令牌",
                    "type": "string"
                },
                "refresh_token": {
                    "description": "刷新令牌",
                    "type": "string"
                }
            }
        },
        "jwt.KickRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "jwt.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "jwt.LogoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "description": "刷新令牌",
                    "type": "string"
                }
            }
        },
        "jwt.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "description": "刷新令牌",
                    "type": "string"
                }
            }
        },
        "message.Body": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "正文",
                    "type": "string"
                },
                "encrypted_content": {
                    "description": "加密正文, 仅在账户控制台可查看",
                    "type": "string"
                },
                "level": {
                    "description": "等级",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "type": {
                    "description": "类型",
                    "type": "string"
                }
            }
        },
        "message.ChangeStatusRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string",
                    "enum": [
                        "pending",
                        "success",
                        "failure"
                    ]
                }
            }
        },
        "message.CreateRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "description": "消息内容",
                    "type": "string"
                },
                "encrypted_content": {
                    "description": "加密消息内容, 仅在账户控制台可查看",
                    "type": "string"
                },
                "level": {
                    "description": "消息等级",
                    "type": "string",
                    "enum": [
                        "info",
                        "warning",
                        "critical"
                    ]
                },
                "title": {
                    "description": "消息标题",
                    "type": "string"
                },
                "type": {
                    "description": "消息类型",
                    "type": "string",
                    "enum": [
                        "text",
                        "markdown"
                    ]
                }
            }
        },
        "message.Message": {
            "type": "object",
            "properties": {
                "_id": {
                    "description": "消息Id",
                    "type": "string"
                },
                "account_id": {
                    "description": "账户Id",
                    "type": "integer"
                },
                "body": {
                    "description": "消息体",
                    "allOf": [
                        {
                            "$ref": "#/definitions/message.Body"
                        }
                    ]
                },
                "channel_api_key": {
                    "description": "通道ApiKey",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "payload": {
                    "description": "附加信息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "integer"
                }
            }
        },
        "message.Messages": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "消息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/message.Message"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
